### ISSUE TITLE
Program execution problem

### ISSUE THREAD

**Issue by 2huoZhang** [minogame/icml2020-TNGA#1]
Hi,I am studying your paper and trying to repeat your experiment, but I have met some problems. I hope to get your help.
The main problems are：
1. What is your data.npy and data.npz file，they seem small
2. The file path in the program is missing some files, but the code says.Such as job_pool.

**Comment by minogame** [comment]
> Hi,I am studying your paper and trying to repeat your experiment, but I have met some problems. I hope to get your help. The main problems are：
> 
> 1. What is your data.npy and data.npz file，they seem small

These are the data file to run. You can provide your own data such that the program will search the best adj_matrix for you.

> 2. The file path in the program is missing some files, but the code says.Such as job_pool.

The program should mkdir these folder automatically. If it doesn't due to the permission, then you could try mkdir by yourself.
